FLOOR_OFFSET = 'Height Offset From Level'
ROUNDING_DECIMALS = 2
MASTORON_COLORSCHEME = 'mastoron.colorscheme'
SAVE = 'Save'
GRADIENTS = 'Gradients'
NAME = 'name'
DATA = 'data'
IS_INSTANCE = 'isInstance'
PARAM_TYPE = 'paramType'